apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: iherb.local
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 5001
          - path: /api/payment
            pathType: Prefix
            backend:
              service:
                name: payment-srv
                port:
                  number: 5002
          - path: /api/product
            pathType: Prefix
            backend:
              service:
                name: product-srv
                port:
                  number: 5003
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-srv
                port:
                  number: 5004
          - path: /api/review
            pathType: Prefix
            backend:
              service:
                name: review-srv
                port:
                  number: 5005
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-srv
                port:
                  number: 5173
